name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        if: success()
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install

      - name: Build
        if: success()
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: build

      - name: Build and Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
